/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsInt,
  IsOptional,
  IsNumber,
  ValidateNested,
  IsString,
} from "class-validator";
import { ExchangeWhereUniqueInput } from "../../exchange/base/ExchangeWhereUniqueInput";
import { Type } from "class-transformer";
import { TradeUpdateManyWithoutStocksInput } from "./TradeUpdateManyWithoutStocksInput";

@InputType()
class StockUpdateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  avgVolume?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  dividendYield?: number | null;

  @ApiProperty({
    required: false,
    type: () => ExchangeWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ExchangeWhereUniqueInput)
  @IsOptional()
  @Field(() => ExchangeWhereUniqueInput, {
    nullable: true,
  })
  exchange?: ExchangeWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  industry?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  marketCap?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  peRatio?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  price?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  sector?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  ticker?: string | null;

  @ApiProperty({
    required: false,
    type: () => TradeUpdateManyWithoutStocksInput,
  })
  @ValidateNested()
  @Type(() => TradeUpdateManyWithoutStocksInput)
  @IsOptional()
  @Field(() => TradeUpdateManyWithoutStocksInput, {
    nullable: true,
  })
  trades?: TradeUpdateManyWithoutStocksInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  website?: string | null;
}

export { StockUpdateInput as StockUpdateInput };
